# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=250, null=True)),
                ('name', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
